<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_administrator</name>
   <tag></tag>
   <elementGuidId>08247516-9be1-4eb5-b1bd-e6b4a8fc18a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesian'])[1]/following::span[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.d-block.fw-500</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7b777dfa-01ec-40ec-b2a1-7e2bdfc56104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-block fw-500</value>
      <webElementGuid>2ee6e87c-4f32-4208-bbbf-0739c7c4d619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>administrator</value>
      <webElementGuid>46bce11c-9df0-40d4-99fc-568f065c0028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;side-menu-closed&quot;]/div[@class=&quot;aiz-main-wrapper&quot;]/div[@class=&quot;aiz-content-wrapper&quot;]/div[@class=&quot;aiz-topbar px-15px px-lg-25px d-flex align-items-stretch justify-content-between&quot;]/div[@class=&quot;d-flex justify-content-between align-items-stretch flex-grow-xl-1&quot;]/div[@class=&quot;d-flex justify-content-around align-items-center align-items-stretch&quot;]/div[@class=&quot;aiz-topbar-item ml-2&quot;]/div[@class=&quot;align-items-stretch d-flex dropdown&quot;]/a[@class=&quot;dropdown-toggle no-arrow text-dark&quot;]/span[@class=&quot;d-flex align-items-center&quot;]/span[@class=&quot;d-none d-md-block&quot;]/span[@class=&quot;d-block fw-500&quot;]</value>
      <webElementGuid>132182cf-bbf8-4274-998a-4bf9924cd74c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesian'])[1]/following::span[4]</value>
      <webElementGuid>1f119a93-a219-40b3-a1a1-d15ff3e7ad4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View All Notifications'])[1]/following::span[6]</value>
      <webElementGuid>1170ab3d-a070-420f-b9f3-51d5d5290562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin'])[1]/preceding::span[1]</value>
      <webElementGuid>5daca7e4-606a-4795-b3e4-e86c62c851c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile'])[1]/preceding::span[2]</value>
      <webElementGuid>1cb1ce02-4451-42cb-a890-5632b38ebd82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='administrator']/parent::*</value>
      <webElementGuid>81e91907-b700-4f86-8760-f02b31ccf5fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span</value>
      <webElementGuid>c5ce7c56-6043-4134-848c-4b8864fb04d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'administrator' or . = 'administrator')]</value>
      <webElementGuid>b764d367-ec26-4446-99d6-2040261a5984</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
